org: firesci
service: ps-daily-wims-feed
frameworkVersion: '3'

plugins:
  - serverless-better-credentials
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    fileName: requirements.txt
    dockerizePip: non-linux

package:
  patterns:
    - '!.venv'
    - '!.mypy_cache'
    - '!parse_stations'
    - '!notes'
    - '!tests'
    - '!node_modules'

provider:
  name: aws
  region: us-west-2
  stage: v1
  profile: management-admin
  runtime: python3.8
  timeout: 900 # 15 min
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 3
  iam:
    role:
      name: PSDailyWIMSLambdaRole
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - "s3:GetObject"
            - "s3:GetObjectAcl"
          Resource:
            - 'arn:aws:s3:::predictive-services-open-data-us-west-2/*'
            - 'arn:aws:s3:::predictive-services-open-data-us-west-2'
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource:
            - '*'

functions:
  cronHandler:
    # Handler is where our code lives
    handler: wims_feed.handler.run
    events:
      # Invoke Lambda every day at 2330z
      - schedule: cron(30 23 * * ? *)

resources:
  Resources:
    PublicDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: predictive-services-open-data-us-west-2
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: ndfd_predserv_fcst.txt
        VersioningConfiguration:
          Status: Enabled
    PublicDataBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        PolicyDocument:
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action:
                - 's3:GetObject'
              Resource: arn:aws:s3:::predictive-services-open-data-us-west-2/*
        Bucket:
          Ref: PublicDataBucket
